<?php

namespace ITHilbert\CookieDisclaimer\Database\Seeders;

use Illuminate\Database\Seeder;

class CookieInfosTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {


        \DB::table('cookie_infos')->delete();

        \DB::table('cookie_infos')->insert(array (
            0 =>
            array (
                'id' => 1,
                'Anbieter' => 'Google',
                'Typ' => 'Analyse',
                'ScriptName' => 'Universal Analytics',
                'Cookie' => '_ga',
                'Geltungsbereich' => 'Diese Domain (1st Party)',
                'Zweck' => 'Enthält eine zufallsgenerierte User-ID. Anhand dieser ID kann Google Analytics wiederkehrende User auf dieser Website wiedererkennen und die Daten von früheren Besuchen zusammenführen. 	',
                'Speicherdauer' => '2 Jahre',
                'Hinweis' => '',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            1 =>
            array (
                'id' => 2,
                'Anbieter' => 'Google',
                'Typ' => 'Analyse',
                'ScriptName' => 'Universal Analytics',
                'Cookie' => '_gid',
                'Geltungsbereich' => 'Diese Domain (1st Party)',
                'Zweck' => 'Enthält eine zufallsgenerierte User-ID. Anhand dieser ID kann Google Analytics wiederkehrende User auf dieser Website wiedererkennen und die Daten von früheren Besuchen zusammenführen.',
                'Speicherdauer' => '24 Stunden',
                'Hinweis' => '',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            2 =>
            array (
                'id' => 3,
                'Anbieter' => 'Google',
                'Typ' => 'Analyse',
                'ScriptName' => 'Universal Analytics',
                'Cookie' => '_gat',
                'Geltungsbereich' => 'Diese Domain (1st Party)',
                'Zweck' => 'Bestimmte Daten werden nur maximal einmal pro Minute an Google Analytics gesendet. Das Cookie hat eine Lebensdauer von einer Minute. Solange es gesetzt ist, werden bestimmte Datenübertragungen unterbunden.',
                'Speicherdauer' => '1 Minute',
                'Hinweis' => 'Wenn Sie Google Analytics über den Google Tag Manager einbinden, heißt das Cookie _dc_gtm_xxx, wobei xxx für Ihre Google Analytics Property ID steht (z.B. _dc_gtm_UA-39737385-2). Wenn Sie den gTag zur Einbindung nutzen, heißt dieses Cookie _ga_gtag_xxx. In allen anderen Fällen heißt das Cookie _gat.',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            3 =>
            array (
                'id' => 4,
                'Anbieter' => 'Google',
                'Typ' => 'Analyse',
                'ScriptName' => 'Universal Analytics',
                'Cookie' => '_dc_gtm_xxx',
                'Geltungsbereich' => 'Diese Domain (1st Party)',
                'Zweck' => 'Bestimmte Daten werden nur maximal einmal pro Minute an Google Analytics gesendet. Das Cookie hat eine Lebensdauer von einer Minute. Solange es gesetzt ist, werden bestimmte Datenübertragungen unterbunden.',
                'Speicherdauer' => '1 Minute',
                'Hinweis' => 'Wenn Sie Google Analytics über den Google Tag Manager einbinden, heißt das Cookie _dc_gtm_xxx, wobei xxx für Ihre Google Analytics Property ID steht (z.B. _dc_gtm_UA-39737385-2). Wenn Sie den gTag zur Einbindung nutzen, heißt dieses Cookie _ga_gtag_xxx. In allen anderen Fällen heißt das Cookie _gat.',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            4 =>
            array (
                'id' => 5,
                'Anbieter' => 'Google',
                'Typ' => 'Analyse',
                'ScriptName' => 'Universal Analytics',
                'Cookie' => '_gat_gtag_xxx',
                'Geltungsbereich' => 'Diese Domain (1st Party)',
                'Zweck' => 'Enthält eine zufallsgenerierte User-ID. Anhand dieser ID kann Google Analytics wiederkehrende User auf dieser Website wiedererkennen und die Daten von früheren Besuchen zusammenführen.',
                'Speicherdauer' => '1 Minute',
                'Hinweis' => 'Wenn Sie Google Analytics über den Google Tag Manager einbinden, heißt das Cookie _dc_gtm_xxx, wobei xxx für Ihre Google Analytics Property ID steht (z.B. _dc_gtm_UA-39737385-2). Wenn Sie den gTag zur Einbindung nutzen, heißt dieses Cookie _ga_gtag_xxx. In allen anderen Fällen heißt das Cookie _gat.',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            5 =>
            array (
                'id' => 6,
                'Anbieter' => 'Google',
                'Typ' => 'Analyse',
                'ScriptName' => 'Universal Analytics',
                'Cookie' => '_gac_xxx',
                'Geltungsbereich' => 'Diese Domain (1st Party)',
                'Zweck' => 'Dieses Cookie wird gesetzt, wenn ein User über einen Klick auf eine Google Werbeanzeige auf die Website gelangt. Es enthält Informationen darüber, welche Werbeanzeige geklickt wurde, sodass erzielte Erfolge wie z.B. Bestellungen oder Kontaktanfragen der Anzeige zugewiesen werden können.',
                'Speicherdauer' => '24 Stunden',
                'Hinweis' => 'Dieses Cookie wird gesetzt, wenn Sie Google Ads schalten und Ihr Google Ads Konto mit der Google Analytics Property verknüpft wurde. xxx im Cookiename stellt dabei einen Platzhalter für Ihre Google Analytics Property ID dar.',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            6 =>
            array (
                'id' => 7,
                'Anbieter' => 'Google',
                'Typ' => 'Analyse',
                'ScriptName' => 'Universal Analytics',
                'Cookie' => 'IDE',
                'Geltungsbereich' => 'doubleclick.net (3rd Party)',
                'Zweck' => 'Enthält eine zufallsgenerierte User-ID. Anhand dieser ID kann Google den User über verschiedene Websites domainübergreifend wiedererkennen und personalisierte Werbung ausspielen.',
                'Speicherdauer' => '1 Jahr',
                'Hinweis' => 'Dieses Cookie wird nur dann gesetzt, wenn Sie die optionale Remarketing-Funktion, die demografischen Berichte oder Google Signals in den Google Analytics Einstellungen aktiviert haben.',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),

            //###########################################
            7 =>
            array (
                'id' => 8,
                'Anbieter' => 'Google',
                'Typ' => 'Analyse',
                'ScriptName' => 'Classic Analytics',
                'Cookie' => '__utma',
                'Geltungsbereich' => 'Diese Domain (1st Party)',
                'Zweck' => 'Enthält eine zufallsgenerierte User-ID. Anhand dieser ID kann Google Analytics wiederkehrende User auf dieser Website wiedererkennen und die Daten von früheren Besuchen zusammenführen.',
                'Speicherdauer' => '2 Jahre',
                'Hinweis' => '',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            7 =>
            array (
                'id' => 8,
                'Anbieter' => 'Google',
                'Typ' => 'Analyse',
                'ScriptName' => 'Classic Analytics',
                'Cookie' => '__utma',
                'Geltungsbereich' => 'Diese Domain (1st Party)',
                'Zweck' => 'Enthält eine zufallsgenerierte User-ID. Anhand dieser ID kann Google Analytics wiederkehrende User auf dieser Website wiedererkennen und die Daten von früheren Besuchen zusammenführen.',
                'Speicherdauer' => '2 Jahre',
                'Hinweis' => '',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            8 =>
            array (
                'id' => 9,
                'Anbieter' => 'Google',
                'Typ' => 'Analyse',
                'ScriptName' => 'Classic Analytics',
                'Cookie' => '__utmb',
                'Geltungsbereich' => 'Diese Domain (1st Party)',
                'Zweck' => 'Enthält eine zufallsgenerierte Session-ID. Dieses Cookie hat eine Speicherdauer von nur 30 Minuten. Alle Aktionen, die ein User innerhalb dieser Zeitspanne auf der Website tätigt, werden in Google Analytics zu einem "Besuch" (einer Session) zusammengefasst.',
                'Speicherdauer' => '30 Minuten',
                'Hinweis' => '',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            9 =>
            array (
                'id' => 10,
                'Anbieter' => 'Google',
                'Typ' => 'Analyse',
                'ScriptName' => 'Classic Analytics',
                'Cookie' => '__utmc',
                'Geltungsbereich' => 'Diese Domain (1st Party)',
                'Zweck' => 'Enthält eine zufallsgenerierte Session-ID. Dieses Cookie wird nicht mehr aktiv genutzt und nur noch aus Kompatibilitätsgründen zu einer älteren Version von Google Analytics gesetzt.',
                'Speicherdauer' => 'Bis zum Schließen des Browsers',
                'Hinweis' => '',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),

            10 =>
            array (
                'id' => 11,
                'Anbieter' => 'Google',
                'Typ' => 'Analyse',
                'ScriptName' => 'Classic Analytics',
                'Cookie' => '__utmt',
                'Geltungsbereich' => 'Diese Domain (1st Party)',
                'Zweck' => 'Bestimmte Daten werden nur maximal einmal pro 10 Minuten an Google Analytics gesendet. Das Cookie hat eine Lebensdauer von 10 Minuten. Solange es gesetzt ist, werden bestimmte Datenübertragungen unterbunden.',
                'Speicherdauer' => '10 Minuten',
                'Hinweis' => '',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),

            11 =>
            array (
                'id' => 12,
                'Anbieter' => 'Google',
                'Typ' => 'Analyse',
                'ScriptName' => 'Classic Analytics',
                'Cookie' => '__utmz',
                'Geltungsbereich' => 'Diese Domain (1st Party)',
                'Zweck' => 'Dieses Cookie speichert Informationen darüber, aus welcher Quelle (von welcher anderen Website bzw. über welche Werbeanzeige) ein User zuletzt auf die Website gekommen ist.',
                'Speicherdauer' => '6 Monate',
                'Hinweis' => '',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),

            12 =>
            array (
                'id' => 13,
                'Anbieter' => 'Google',
                'Typ' => 'Analyse',
                'ScriptName' => 'Classic Analytics',
                'Cookie' => '__utmv',
                'Geltungsbereich' => 'Diese Domain (1st Party)',
                'Zweck' => 'Dieses Cookie speichert User-bezogene Daten, die von der Website an Google Analytics übergeben wurden.',
                'Speicherdauer' => '2 Jahre',
                'Hinweis' => 'Dieses Cookie wird nur gesetzt, wenn Sie benutzerdefinierte Variablen mit User-Scope an Google Analytics übertragen (mit der _setVar() bzw. der  _setCustomVar()-Funktion). Welche Informationen konkret gespeichert werden, müssen Sie selbst angeben.',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),

            13 =>
            array (
                'id' => 14,
                'Anbieter' => 'Google',
                'Typ' => 'Analyse',
                'ScriptName' => 'Classic Analytics',
                'Cookie' => '__utmx',
                'Geltungsbereich' => 'Diese Domain (1st Party)',
                'Zweck' => 'Über Google Analytics können testweise alternative Versionen derselben Seite ausgespielt werden, um zu prüfen, welche von Usern besser angenommen wird ("A/B-Testing"). Dieses Cookie enthält Informationen, an welchen Tests der User teilgenommen hat.',
                'Speicherdauer' => '18 Monate',
                'Hinweis' => 'Diese Cookies werden nur gesetzt, wenn Sie die "Content Experimente" Funktion von Google Analytics aktiv einsetzen.',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),

            14 =>
            array (
                'id' => 15,
                'Anbieter' => 'Google',
                'Typ' => 'Analyse',
                'ScriptName' => 'Classic Analytics',
                'Cookie' => '__utmxx',
                'Geltungsbereich' => 'Diese Domain (1st Party)',
                'Zweck' => 'Über Google Analytics können testweise alternative Versionen derselben Seite ausgespielt werden, um zu prüfen, welche von Usern besser angenommen wird ("A/B-Testing"). Dieses Cookie enthält Informationen, an welchen Tests der User teilgenommen hat bzw. wann der Test endet.',
                'Speicherdauer' => '18 Monate',
                'Hinweis' => 'Diese Cookies werden nur gesetzt, wenn Sie die "Content Experimente" Funktion von Google Analytics aktiv einsetzen.',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),

            15 =>
            array (
                'id' => 16,
                'Anbieter' => 'Google',
                'Typ' => 'Analyse',
                'ScriptName' => 'Classic Analytics',
                'Cookie' => 'IDE',
                'Geltungsbereich' => 'doubleclick.net (3rd Party)',
                'Zweck' => 'Enthält eine zufallsgenerierte User-ID. Anhand dieser ID kann Google den User über verschiedene Websites domainübergreifend wiedererkennen und personalisierte Werbung ausspielen.',
                'Speicherdauer' => '1 Jahr',
                'Hinweis' => 'Dieses Cookie wird nur dann gesetzt, wenn Sie die optionale Remarketing-Funktion, die demografischen Berichte oder Google Signals in den Google Analytics Einstellungen aktiviert haben.',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            //###########################################
            16 =>
            array (
                'id' => 17,
                'Anbieter' => 'Google',
                'Typ' => 'Marketing',
                'ScriptName' => 'Google Ads und Google Display & Video 360',
                'Cookie' => 'test_cookie',
                'Geltungsbereich' => 'doubleclick.net (3rd Party)',
                'Zweck' => 'Wird testweise gesetzt, um zu prüfen, ob der Browser das Setzen von Cookies erlaubt. Enthält keine Identifikationsmerkmale.',
                'Speicherdauer' => '15 Minuten',
                'Hinweis' => '',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),

            17 =>
            array (
                'id' => 18,
                'Anbieter' => 'Google',
                'Typ' => 'Marketing',
                'ScriptName' => 'Google Ads und Google Display & Video 360',
                'Cookie' => 'IDE',
                'Geltungsbereich' => 'doubleclick.net (3rd Party)',
                'Zweck' => 'Enthält eine zufallsgenerierte User-ID. Anhand dieser ID kann Google den User über verschiedene Websites domainübergreifend wiedererkennen und personalisierte Werbung ausspielen.',
                'Speicherdauer' => '1 Jahr',
                'Hinweis' => '',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            //###########################################
            18 =>
            array (
                'id' => 19,
                'Anbieter' => 'Google',
                'Typ' => 'Marketing',
                'ScriptName' => 'Conversion Linker / Conversion Verknüpfung',
                'Cookie' => '_gcl_au',
                'Geltungsbereich' => 'Diese Domain (1st Party)',
                'Zweck' => 'Enthält eine zufallsgenerierte User-ID.',
                'Speicherdauer' => '90 Tage',
                'Hinweis' => '',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),

            19 =>
            array (
                'id' => 20,
                'Anbieter' => 'Google',
                'Typ' => 'Marketing',
                'ScriptName' => 'Conversion Linker / Conversion Verknüpfung',
                'Cookie' => '_gcl_aw',
                'Geltungsbereich' => 'Diese Domain (1st Party)',
                'Zweck' => 'Dieses Cookie wird gesetzt, wenn ein User über einen Klick auf eine Google Werbeanzeige auf die Website gelangt. Es enthält Informationen darüber, welche Werbeanzeige geklickt wurde, sodass erzielte Erfolge wie z.B. Bestellungen oder Kontaktanfragen der Anzeige zugewiesen werden können.',
                'Speicherdauer' => '90 Tage',
                'Hinweis' => 'Wenn Google Ads (inkl. automatischer Tag-Kennzeichnung) verwendet wird.',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),

            20 =>
            array (
                'id' => 21,
                'Anbieter' => 'Google',
                'Typ' => 'Marketing',
                'ScriptName' => 'Conversion Linker / Conversion Verknüpfung',
                'Cookie' => '_gcl_dc',
                'Geltungsbereich' => 'Diese Domain (1st Party)',
                'Zweck' => 'Dieses Cookie wird gesetzt, wenn ein User über einen Klick auf eine Google Werbeanzeige auf die Website gelangt. Es enthält Informationen darüber, welche Werbeanzeige geklickt wurde, sodass erzielte Erfolge wie z.B. Bestellungen oder Kontaktanfragen der Anzeige zugewiesen werden können.',
                'Speicherdauer' => '90 Tage',
                'Hinweis' => 'Wenn Display & Video 360 (inkl. erweiterter Attribution) verwendet wird.',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            //###########################################

            21 =>
            array (
                'id' => 22,
                'Anbieter' => 'Google',
                'Typ' => 'Marketing',
                'ScriptName' => 'Google Optimize',
                'Cookie' => '_gaexp',
                'Geltungsbereich' => 'Diese Domain (1st Party)',
                'Zweck' => 'Wird testweise gesetzt, um zu prüfen, ob der Browser das Setzen von Cookies erlaubt. Enthält keine Identifikationsmerkmale.',
                'Speicherdauer' => '90 Tage',
                'Hinweis' => '',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),

            22 =>
            array (
                'id' => 23,
                'Anbieter' => 'Google',
                'Typ' => 'Marketing',
                'ScriptName' => 'Google Optimize',
                'Cookie' => '_opt_utmc',
                'Geltungsbereich' => 'Diese Domain (1st Party)',
                'Zweck' => 'Dieses Cookie speichert Informationen darüber, über welche Marketing-Kampagne ein User zuletzt auf die Website gekommen ist.',
                'Speicherdauer' => '24 Stunden',
                'Hinweis' => '',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),

            23 =>
            array (
                'id' => 24,
                'Anbieter' => 'Google',
                'Typ' => 'Marketing',
                'ScriptName' => 'Google Optimize',
                'Cookie' => '_opt_awcid',
                'Geltungsbereich' => 'Diese Domain (1st Party)',
                'Zweck' => 'Enthält eine zufallsgenerierte User-ID. Anhand dieser ID kann Google den User über verschiedene Websites domainübergreifend wiedererkennen und personalisierte Werbung ausspielen.',
                'Speicherdauer' => '24 Stunden',
                'Hinweis' => '',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),

            24 =>
            array (
                'id' => 25,
                'Anbieter' => 'Google',
                'Typ' => 'Marketing',
                'ScriptName' => 'Google Optimize',
                'Cookie' => '_opt_awmid',
                'Geltungsbereich' => 'Diese Domain (1st Party)',
                'Zweck' => 'Dieses Cookie wird gesetzt, wenn ein User über einen Klick auf eine Google Werbeanzeige auf die Website gelangt. Es enthält Informationen darüber, aus wessen Kundenkonto die angeklickte Werbeanzeige geschalten wurde.',
                'Speicherdauer' => '24 Stunden',
                'Hinweis' => '',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),

            25 =>
            array (
                'id' => 26,
                'Anbieter' => 'Google',
                'Typ' => 'Marketing',
                'ScriptName' => 'Google Optimize',
                'Cookie' => '_opt_awgid',
                'Geltungsbereich' => 'Diese Domain (1st Party)',
                'Zweck' => 'Dieses Cookie wird gesetzt, wenn ein User über einen Klick auf eine Google Werbeanzeige auf die Website gelangt. Es enthält Informationen darüber, zu welcher Werbekampagne die angeklickte Werbeanzeige gehört.',
                'Speicherdauer' => '24 Stunden',
                'Hinweis' => '',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),

            26 =>
            array (
                'id' => 27,
                'Anbieter' => 'Google',
                'Typ' => 'Marketing',
                'ScriptName' => 'Google Optimize',
                'Cookie' => '_opt_awkid',
                'Geltungsbereich' => 'Diese Domain (1st Party)',
                'Zweck' => 'Dieses Cookie wird gesetzt, wenn ein User über einen Klick auf eine Google Werbeanzeige auf die Website gelangt. Es enthält Informationen darüber, aufgrund welcher Auswahlkriterien die Anzeige geschalten wurde, beispielsweise welches Keyword bei Google eingebucht wurde.',
                'Speicherdauer' => '24 Stunden',
                'Hinweis' => '',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            //###########################################
            27 =>
            array (
                'id' => 28,
                'Anbieter' => 'facebook',
                'Typ' => 'Marketing',
                'ScriptName' => 'Facebook',
                'Cookie' => '_fbp',
                'Geltungsbereich' => 'Diese Domain (1st Party)',
                'Zweck' => 'Enthält eine zufallsgenerierte User-ID und den Zeitpunkt Ihres ersten Besuchs. Anhand dieser ID kann Facebook wiederkehrende User auf dieser Website wiedererkennen und die Daten von früheren Besuchen zusammenführen.',
                'Speicherdauer' => '90 Tage',
                'Hinweis' => '',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),

            28 =>
            array (
                'id' => 29,
                'Anbieter' => 'facebook',
                'Typ' => 'Marketing',
                'ScriptName' => 'Facebook',
                'Cookie' => '_fbc',
                'Geltungsbereich' => 'Diese Domain (1st Party)',
                'Zweck' => 'Dieses Cookie wird gesetzt, wenn ein User über einen Klick auf eine Facebook Werbeanzeige auf die Website gelangt. Es enthält Informationen darüber, welche Werbeanzeige geklickt wurde, sodass erzielte Erfolge wie z.B. Bestellungen oder Kontaktanfragen der Anzeige zugewiesen werden können',
                'Speicherdauer' => '90 Tage',
                'Hinweis' => '',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            //###########################################
            29 =>
            array (
                'id' => 30,
                'Anbieter' => 'Microsoft',
                'Typ' => 'Marketing',
                'ScriptName' => 'Microsoft Advertising / Bing Ads',
                'Cookie' => '_uetsid',
                'Geltungsbereich' => 'Diese Domain (1st Party)',
                'Zweck' => 'Enthält eine zufallsgenerierte Session-ID. Anhand dieser ID kann Microsoft mehrere Einzelaktionen (Seitenaufrufe, Klicks, Bestellungen, ...) als zusammenhängende Sitzung (ein einzelner Website-Besuch) erfassen.',
                'Speicherdauer' => '24 Stunden',
                'Hinweis' => '',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            30 =>
            array (
                'id' => 31,
                'Anbieter' => 'Microsoft',
                'Typ' => 'Marketing',
                'ScriptName' => 'Microsoft Advertising / Bing Ads',
                'Cookie' => '_uetvid',
                'Geltungsbereich' => 'Diese Domain (1st Party)',
                'Zweck' => 'Enthält eine zufallsgenerierte User-ID. Anhand dieser ID kann Microsoft wiederkehrende User auf dieser Website wiedererkennen und die Daten von früheren Besuchen zusammenführen.',
                'Speicherdauer' => '4 Wochen',
                'Hinweis' => '',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            31 =>
            array (
                'id' => 32,
                'Anbieter' => 'Microsoft',
                'Typ' => 'Marketing',
                'ScriptName' => 'Microsoft Advertising / Bing Ads',
                'Cookie' => '_uetmsclkid',
                'Geltungsbereich' => 'Diese Domain (1st Party)',
                'Zweck' => 'Dieses Cookie wird gesetzt, wenn ein User über einen Klick auf eine Microsoft Bing Werbeanzeige auf die Website gelangt. Es enthält Informationen darüber, aufgrund welcher Auswahlkriterien die Anzeige geschalten wurde, beispielsweise welcher Suchbegriff bei Bing für die Werbeschaltung eingebucht wurde. Dadurch können erzielte Werbeerfolge konkreten Bing-Kampagnen zugeordnet werden.',
                'Speicherdauer' => '3 Monate',
                'Hinweis' => '',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            //###########################################
            32 =>
            array (
                'id' => 33,
                'Anbieter' => 'mouseflow',
                'Typ' => 'Marketing',
                'ScriptName' => 'Mouseflow',
                'Cookie' => 'mf_user',
                'Geltungsbereich' => 'Diese Domain (1st Party)',
                'Zweck' => 'Enthält eine zufallsgenerierte User-ID. Anhand dieser ID kann Mouseflow wiederkehrende User auf dieser Website wiedererkennen und die Daten von früheren Besuchen zusammenführen.',
                'Speicherdauer' => '90 Tage',
                'Hinweis' => '',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            33 =>
            array (
                'id' => 34,
                'Anbieter' => 'Mouseflow',
                'Typ' => 'Marketing',
                'ScriptName' => 'Mouseflow',
                'Cookie' => 'mf_xxx',
                'Geltungsbereich' => 'Diese Domain (1st Party)',
                'Zweck' => 'Kurzfristiges Cookie, das nach dem Verlassen der Website automatisch wieder gelöscht wird. Enthält u.a. ein zufallsgenerierte Session-ID, sodass alle Seitenaufrufe und Aktionen während eines Website-Besuchs als zusammenhängende Serie von Aktionen interpretiert werden kann.',
                'Speicherdauer' => 'Session (bis zum Verlassen der Website)',
                'Hinweis' => 'xxx im Cookiename stellt dabei einen Platzhalter für Ihre Mouseflow ID dar - beispielsweise mf_cc696e05-a68b-4d59-bc75-c97b2eac54ce.',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            //###########################################
            34 =>
            array (
                'id' => 35,
                'Anbieter' => 'diese Domain',
                'Typ' => 'Funktion',
                'ScriptName' => 'Laravel Framework',
                'Cookie' => 'XSRF-TOKEN',
                'Geltungsbereich' => 'Diese Domain (1st Party)',
                'Zweck' => 'Sicherheitsfunktion von Laravel',
                'Speicherdauer' => '1 Woche',
                'Hinweis' => '',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            35 =>
            array (
                'id' => 36,
                'Anbieter' => 'diese Domain',
                'Typ' => 'Funktion',
                'ScriptName' => 'Laravel Framework',
                'Cookie' => '[Domain]_session',
                'Geltungsbereich' => 'Diese Domain (1st Party)',
                'Zweck' => 'Session ID damit der user mit der Seite agieren kann.',
                'Speicherdauer' => '1 Tag',
                'Hinweis' => '[Domain] steht für den Domain Namen z.B. it-hilbert_session',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            36 =>
            array (
                'id' => 37,
                'Anbieter' => 'diese Domain',
                'Typ' => 'Funktion',
                'ScriptName' => 'Laravel Framework',
                'Cookie' => 'remember_web_xxx',
                'Geltungsbereich' => 'Diese Domain (1st Party)',
                'Zweck' => 'Benutzervorgaben zu speichern',
                'Speicherdauer' => '1 Woche',
                'Hinweis' => 'xxx steht für eine Zufällige ID Nummer.',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),

            37 =>
            array (
                'id' => 38,
                'Anbieter' => 'diese Domain',
                'Typ' => 'Funktion',
                'ScriptName' => 'Cookie Disclaimer',
                'Cookie' => 'cookies-allow',
                'Geltungsbereich' => 'Diese Domain (1st Party)',
                'Zweck' => 'Speichert ob der Besucher Okays erlaubt hat.',
                'Speicherdauer' => '30 Tage',
                'Hinweis' => 'Im Cookie wird nur das Datum und die Uhrzeit der Zustimmung gespeichert.',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),

            //###########################################
            38 =>
            array (
                'id' => 39,
                'Anbieter' => 'Google',
                'Typ' => 'Marketing / Werbung',
                'ScriptName' => 'google',
                'Cookie' => '__Secure-3PSIDCC',
                'Geltungsbereich' => 'google.com (3rd Party)',
                'Zweck' => 'Targeting cookie. Wird genutzt, um ein Nutzer Profil zu erstellen und dem Nutzer relevante und personalisierte Google Ads anzuzeigen.',
                'Speicherdauer' => '2 Jahren',
                'Hinweis' => '',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            39 =>
            array (
                'id' => 40,
                'Anbieter' => 'Google',
                'Typ' => 'Marketing / Werbung',
                'ScriptName' => 'google',
                'Cookie' => 'HSID',
                'Geltungsbereich' => 'google.com (3rd Party)',
                'Zweck' => 'Google Analytics-Anpassungscookie. Wird vom Google + 1 sharing button verwendet und ist zum Verknüpfen von Inhalten mit dem Google 1+ -Konto erforderlich.',
                'Speicherdauer' => '2 Jahren',
                'Hinweis' => '',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            41 =>
            array (
                'id' => 42,
                'Anbieter' => 'Google',
                'Typ' => 'Marketing / Werbung',
                'ScriptName' => 'google',
                'Cookie' => '__Secure-3PSID',
                'Geltungsbereich' => 'google.com (3rd Party)',
                'Zweck' => 'Targeting cookie. Wird verwendet, um ein Profil der Interessen, der Website-Besucher zu erstellen und relevante und personalisierte Google-Werbung anzuzeigen.',
                'Speicherdauer' => '2 Jahren',
                'Hinweis' => '',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            42 =>
            array (
                'id' => 43,
                'Anbieter' => 'Google',
                'Typ' => 'Marketing / Werbung',
                'ScriptName' => 'google',
                'Cookie' => 'SID',
                'Geltungsbereich' => 'google.com (3rd Party)',
                'Zweck' => 'Google Analytics-Anpassungscookie. Wird vom Google + 1 sharing button verwendet und ist zum Verknüpfen von Inhalten mit dem Google 1+ -Konto erforderlich.',
                'Speicherdauer' => '2 Jahren',
                'Hinweis' => '',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            43 =>
            array (
                'id' => 44,
                'Anbieter' => 'Google',
                'Typ' => 'Marketing / Werbung',
                'ScriptName' => 'google',
                'Cookie' => 'SAPISID',
                'Geltungsbereich' => 'google.com (3rd Party)',
                'Zweck' => 'Google Analytics-Anpassungscookie. Wird vom Google + 1 sharing button verwendet und ist zum Verknüpfen von Inhalten mit dem Google 1+ -Konto erforderlich.',
                'Speicherdauer' => '2 Jahren',
                'Hinweis' => '',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            44 =>
            array (
                'id' => 45,
                'Anbieter' => 'Google',
                'Typ' => 'Marketing / Werbung',
                'ScriptName' => 'google',
                'Cookie' => 'APISID',
                'Geltungsbereich' => 'google.com (3rd Party)',
                'Zweck' => 'Google sammelt Besucherinformationen für von YouTube ausgespielte Videos.',
                'Speicherdauer' => 'Persistent',
                'Hinweis' => '',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            45 =>
            array (
                'id' => 46,
                'Anbieter' => 'Google',
                'Typ' => 'Marketing / Werbung',
                'ScriptName' => 'google',
                'Cookie' => 'SSID',
                'Geltungsbereich' => 'google.com (3rd Party)',
                'Zweck' => 'Google sammelt Besucherinformationen für von YouTube ausgespielte Videos, die auf integrierten Karten von Google Maps ausgespielt werden.',
                'Speicherdauer' => 'Persistent',
                'Hinweis' => '',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            46 =>
            array (
                'id' => 47,
                'Anbieter' => 'Google',
                'Typ' => 'Marketing / Werbung',
                'ScriptName' => 'google',
                'Cookie' => 'SIDCC',
                'Geltungsbereich' => 'google.com (3rd Party)',
                'Zweck' => 'Sicherheitscookie zur Bestätigung der Besucherauthentizität, zur Verhinderung der betrügerischen Verwendung von Anmeldedaten und zum Schutz der Besucherdaten vor unbefugtem Zugriff.',
                'Speicherdauer' => '3 Monaten',
                'Hinweis' => '',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            47 =>
            array (
                'id' => 48,
                'Anbieter' => 'Google',
                'Typ' => 'Marketing / Werbung',
                'ScriptName' => 'google',
                'Cookie' => '__Secure-3PAPISID',
                'Geltungsbereich' => 'google.com (3rd Party)',
                'Zweck' => 'Erstellt ein Profil der Interessen von Website Besuchern, um relevante und personalisierte Anzeigen durch Retargeting zu schalten.',
                'Speicherdauer' => '2 Jahre',
                'Hinweis' => '',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            48 =>
            array (
                'id' => 49,
                'Anbieter' => 'Google',
                'Typ' => 'Marketing / Werbung',
                'ScriptName' => 'google',
                'Cookie' => '',
                'Geltungsbereich' => 'google.com (3rd Party)',
                'Zweck' => 'Erstellt ein Profil der Interessen von Website Besuchern, um relevante und personalisierte Anzeigen durch Retargeting zu schalten.',
                'Speicherdauer' => '',
                'Hinweis' => '',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            49 =>
            array (
                'id' => 50,
                'Anbieter' => 'Google',
                'Typ' => 'Marketing / Werbung',
                'ScriptName' => 'google',
                'Cookie' => 'DV',
                'Geltungsbereich' => 'google.com (3rd Party)',
                'Zweck' => 'Cookies werden verwendet, um Informationen darüber zu sammeln, wie Besucher unsere Website nutzen. Die Informationen werden verwendet, um Berichte zu erstellen und die Website zu verbessern. Die Cookies sammeln Informationen in anonymer Form, einschließlich der Anzahl der Besucher der Website, woher diese Website Besucher kommen und welche Seiten Sie noch besucht haben. Wenn diese Cookies nicht zugelassen werden, kann Google Analytics den Website Besuch nicht mit in die Statistiken aufnehmen. Vollständige Datenschutzbestimmungen von Google Analytics können hier nachgelesen werden: http://www.google.com/policies/privacy/.',
                'Speicherdauer' => '2 Jahre',
                'Hinweis' => '',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),

            50 =>
            array (
                'id' => 51,
                'Anbieter' => 'Google',
                'Typ' => 'Marketing / Werbung',
                'ScriptName' => 'google',
                'Cookie' => '1P_JAR',
                'Geltungsbereich' => 'google.com (3rd Party)',
                'Zweck' => 'Basierend auf den letzten Suchanfragen und früheren Interaktionen werden benutzerdefinierte Anzeigen auf Google-Websites geschaltet.',
                'Speicherdauer' => '1 Woche',
                'Hinweis' => '',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            51 =>
            array (
                'id' => 52,
                'Anbieter' => 'Google',
                'Typ' => 'Marketing / Werbung',
                'ScriptName' => 'google',
                'Cookie' => 'UULE',
                'Geltungsbereich' => 'google.com (3rd Party)',
                'Zweck' => 'Speichert Ihre bevorzugten Einstellungen',
                'Speicherdauer' => '2 Jahren',
                'Hinweis' => '',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            52 =>
            array (
                'id' => 53,
                'Anbieter' => 'Google',
                'Typ' => 'Marketing / Werbung',
                'ScriptName' => 'google',
                'Cookie' => 'CONSENT',
                'Geltungsbereich' => 'google.com (3rd Party)',
                'Zweck' => 'Speichert die Präferenzen der Besucher und personalisiert Anzeigen.',
                'Speicherdauer' => 'Persistent',
                'Hinweis' => '',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            53 =>
            array (
                'id' => 54,
                'Anbieter' => 'Google',
                'Typ' => 'Marketing / Werbung',
                'ScriptName' => 'google',
                'Cookie' => 'ANID',
                'Geltungsbereich' => 'google.com (3rd Party)',
                'Zweck' => 'Listet Google Ads auf Google-Websites basierend auf den letzten Suchanfragen auf.',
                'Speicherdauer' => 'Persistent',
                'Hinweis' => '',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            54 =>
            array (
                'id' => 55,
                'Anbieter' => 'Google',
                'Typ' => 'Marketing / Werbung',
                'ScriptName' => 'google',
                'Cookie' => 'NID',
                'Geltungsbereich' => 'google.com (3rd Party)',
                'Zweck' => 'Speichert die Präferenzen der Besucher und personalisiert Ads auf Google-Websites basierend auf den letzten Suchanfragen und Interaktionen.',
                'Speicherdauer' => '6 Monaten',
                'Hinweis' => '',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            55 =>
            array (
                'id' => 56,
                'Anbieter' => 'Google',
                'Typ' => 'Marketing / Werbung',
                'ScriptName' => 'google',
                'Cookie' => 'OTZ',
                'Geltungsbereich' => 'google.com (3rd Party)',
                'Zweck' => 'Links activities of website visitors to other devices that are previously logged in via the Google account. In this way, advertisements are tailored to different devices.1 Verknüpft Aktivitäten von Website-Besuchern mit anderen Geräten, die zuvor über das Google-Konto angemeldet waren. Auf diese Weise werden Anzeigen auf verschiedene Geräte zugeschnitten.',
                'Speicherdauer' => '1 Monate',
                'Hinweis' => '',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            56 =>
            array (
                'id' => 57,
                'Anbieter' => 'Google',
                'Typ' => 'Marketing / Werbung',
                'ScriptName' => 'google',
                'Cookie' => 'SEARCH_SAMESITE',
                'Geltungsbereich' => 'google.com (3rd Party)',
                'Zweck' => 'Wird verwendet, um zu verhindern, dass der Browser den Cookie zusammen mit standortübergreifenden Anforderungen sendet.',
                'Speicherdauer' => '2 Jahren',
                'Hinweis' => '',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            57 =>
            array (
                'id' => 58,
                'Anbieter' => 'Google',
                'Typ' => 'Marketing / Werbung',
                'ScriptName' => 'google',
                'Cookie' => 'S_adsense3-ui',
                'Geltungsbereich' => 'google.com (3rd Party)',
                'Zweck' => 'Enthält Informationen darüber, wie der Endbenutzer die Website nutzt.',
                'Speicherdauer' => 'End of session',
                'Hinweis' => '',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            58 =>
            array (
                'id' => 59,
                'Anbieter' => 'Google',
                'Typ' => 'Marketing / Werbung',
                'ScriptName' => 'google',
                'Cookie' => 'S',
                'Geltungsbereich' => 'google.com (3rd Party)',
                'Zweck' => 'Google session cookie',
                'Speicherdauer' => 'End of session',
                'Hinweis' => '',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            59 =>
            array (
                'id' => 60,
                'Anbieter' => 'Google',
                'Typ' => 'Marketing / Werbung',
                'ScriptName' => 'google',
                'Cookie' => '__Secure-3PSIDCC',
                'Geltungsbereich' => 'google.com (3rd Party)',
                'Zweck' => 'Genutzt für das Targeting, um ein Profil der Interessen der Website-Besucher zu erstellen und relevante und personalisierte Google Ads anzuzeigen.',
                'Speicherdauer' => '2 Jahren',
                'Hinweis' => '',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
            60 =>
            array (
                'id' => 61,
                'Anbieter' => 'Google',
                'Typ' => 'Marketing / Werbung',
                'ScriptName' => 'google',
                'Cookie' => 'HSID',
                'Geltungsbereich' => 'google.com (3rd Party)',
                'Zweck' => 'Sicherheitscookie zur Bestätigung der Besucherauthentizität, zur Verhinderung der betrügerischen Verwendung von Anmeldedaten und zum Schutz der Besucherdaten vor unbefugtem Zugriff.',
                'Speicherdauer' => '2 Jahren',
                'Hinweis' => '',
                'created_at' => NULL,
                'updated_at' => NULL,
            ),
        ));


    }
}
